### ISSUE TITLE
Windows: failing tests

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/protozero#40]
Some tests are failing for me locally, but succeed on AppVeyor (maybe `LF` vs. `CRLF` again?):

![image](https://cloud.githubusercontent.com/assets/4549888/11453411/32922e3a-960a-11e5-870b-1cf955dc08ea.png)

**Comment by joto** [comment]
There is a script `test/create_pbf_test_data.sh` that is used to create the reference files using the google protobuf library. Those references are then later compared against the results of the test run. Usually you don't have to create those reference files, because they are checked into the repository. But if you did, they could have been corrupted, because the binary mode was not enabled. The appveyor script doesn't create those files but uses the ones from the repository. So this could explain the different results.

**Comment by BergWerkGIS** [comment]
> There is a script `test/create_pbf_test_data.sh` 

These scripts cannot be executed on the default Windows command line.
I verified that all `testcase.proto` files have not been changed since check out.
But they all have `CRLF` line endings.

-----

Problem is that git changes the line endings of **_some_ `PBF`s**.

e.g. this error 

![image](https://cloud.githubusercontent.com/assets/4549888/11456246/b0a61876-9683-11e5-9a93-4c2d9fe13b9c.png)

disappears if I change the line endings of `test/t/tmessage/data-opt-element.pbf` back to `LF`.
Obviously git has identified `data-opt-element.pbf` as text and changed its line endings to `CRLF` during clone.

**Comment by BergWerkGIS** [comment]
And all test pass if I change `test/t/repeated_packed_double/data-one.pbf` to `LF`.

**Comment by joto** [comment]
I added a `.gitattributes` file. Does that help?

**Comment by BergWerkGIS** [comment]
:+1: 

looking good after a fresh clone:

![image](https://cloud.githubusercontent.com/assets/4549888/11458674/2edb50da-96c5-11e5-88d7-093c4baa467c.png)
