### ISSUE TITLE
Assert if signed ints passed into add_enum?

### ISSUE THREAD

**Issue by springmeyer** [mapbox/protozero#58]
@joto I noticed that the signature of `add_enum` accepts signed int but then turns into unsigned internally. I presume passing in a negative int will lead to unpredictable behavior, or am I missing something? Should we assert if this happens to protect from misuage?

https://github.com/mapbox/protozero/blob/master/include/protozero/pbf_writer.hpp#L341-L353

**Comment by joto** [comment]
The [documentation](https://developers.google.com/protocol-buffers/docs/proto#enum) says: "Enumerator constants must be in the range of a 32-bit integer. Since enum values use varint encoding on the wire, negative values are inefficient and thus not recommended." So, clearly, negative values for enums are allowed and must be handled. So it is correct that this function takes an argument of type `int32_t`.
Casting to an unsigned int is needed because of the way the varint function works. And I believe this operation to be safe and well-defined. (Correct me if I am wrong there.) We don't have a test for this, but the test for int32 (which is essentially the same as enum) contains code to test for negative numbers: https://github.com/mapbox/protozero/blob/master/test/t/int32/testcase.cpp so this should all be okay.

**Comment by springmeyer** [comment]
Okay, thanks for the explanation!

**Comment by joto** [comment]
Just to be on the safe side, I added tests for those enums, too: dc19775129603c8b73d5a53ede1da74f676e830b
