### ISSUE TITLE
Iterator Range Conversion fails on libc++

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/protozero#62]
The iterator range's conversion to pair / tuple fails on libc++.
Here's a small self-contained reproducible test-case:

``` cpp
int main() {
  iterator_range<const int*> range;

  const int* first;
  const int* last;

  std::tie(first, last) = range;
}
```

> it.cc:105:25: error: no viable overloaded '='
>  std::tie(first, last) = range;

Reading the docs:

> std::tie may be used to unpack a std::pair because std::tuple has a converting assignment from pairs

http://en.cppreference.com/w/cpp/utility/tuple/tie

For the record, with stdlibc++ I can force a similar error defining `-DPROTOZERO_STRICT_API` (with both clang 38 as well as gcc 6.2):

> error: ‘std::pair<const int*, const int*>’ is an inaccessible base of ‘iterator_range<const int*>’

With libc++ neither defining nor not defining the symbol makes a difference: both compilations fail.

We hit this today on OSX builds:
https://github.com/Project-OSRM/osrm-backend/pull/2974

**Comment by joto** [comment]
That there is an error when using `-DPROTOZERO_STRICT_API` is on purpose. The whole point of that macro is to dis-allow automatic conversion to `std::pair`, so that you do not rely on this being internally implemented using a `std::pair`. I want to be able to change the internal implementation in the future.

Currently an `iterator_range` should mostly behave like a `std::pair`, because I wanted to allow a migration path between the old implementation where it was a `std::pair`. This is done through the trick of deriving from `std::pair` publically.

I am not sure why `std::tie` doesn't work on libc++ but works on stdlibc++. But instead of trying to figure this out, you can just switch to the new future-proof behaviour and not think of `iterator_range` as a pair. Use `begin()` and `end()` on it like you would with any container to get those iterators out. (Or, even better in many cases, just use range-for on the range.)

**Comment by daniel-j-h** [comment]
Thanks @joto I'm aware of the workarounds.

The different behavior depending on stdlib still is an issue in my opinion. But knowing this is a deprecated protozero code-path anyway, you probably don't have to put much effort into fixing this. I'll add the strict api definition to our buildsystem.
