### ISSUE TITLE
Undefined Behavior due to Type Punning

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/protozero#64]
https://github.com/mapbox/protozero/blob/f5ea37d5b431024de6f87a95c9b0226b850d2ef4/include/protozero/byteswap.hpp#L35-L67

These functions casts a `char* ` (alignment requirement of 1) to a `uint32/64_t *` (higher alignment requirement). This is undefined behavior and can fail e.g. on platforms other than x86 or if you enable SSE and the compiler wants to make use of alignment guarantees.

All of these have to go through a [bit_cast](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0476r0.html) (see e.g. https://github.com/jfbastien/bit_cast for JF's proposal).

**Comment by joto** [comment]
We can't guarantee alignment to anything here. I don't see how `bitcast` would help us, because we already use the byteswap functions in a place where we want to copy the data to get it to the correct alignment.
But we already have the `#ifdef PROTOZERO_USE_BUILTIN_BSWAP` check to choose the (hopefully faster) builtin or the slow version which should be always okay. Maybe we can extend [the check](https://github.com/mapbox/protozero/blob/f5ea37d5b431024de6f87a95c9b0226b850d2ef4/include/protozero/config.hpp#L50-L52) that decides whether `PROTOZERO_USE_BUILTIN_BSWAP` is defined somehow to fail on architectures where it would not work.

**Comment by daniel-j-h** [comment]
The issue is not the bswap impl. it's the following pattern

    *reinterpret_cast<uint32_t*>(result)

This increases the alignment requirements (`char` -> `uint32_t`) and is undefined behavior.

**Comment by joto** [comment]
I am aware of that. But that cast is only called when `PROTOZERO_USE_BUILTIN_BSWAP` is defined.
