### ISSUE TITLE
Avoiding -Wswitch-enum warning

### ISSUE THREAD

**Issue by springmeyer** [mapbox/protozero#72]
@joto - this is a very minor issue, but this warning comes up when downstream users of protozero turn on `-Weverything` with clang++:

```
../mason_packages/.link/include/protozero/pbf_reader.hpp:290:17: warning: enumeration value 'unknown' not explicitly handled in switch [-Wswitch-enum]
        switch (m_wire_type) {
                ^
../mason_packages/.link/include/protozero/pbf_reader.hpp:389:17: warning: enumeration value 'unknown' not explicitly handled in switch [-Wswitch-enum]
        switch (wire_type()) {
                ^
```

Would it be reasonable to explicitly handle `case pbf_wire_type::unknown` in order to avoid this warning?

**Comment by joto** [comment]
Compiling with `-Weverything` will throw a lot more warnings than that. Most not really useful. In this case we can't really do better, because if we add `case pbf_wire_type::unknown` the `default` case becomes superfluous to the compiler and some compilers will warn then. But it is not superfluous, because we know that other values not in the enum can be in there, because this is data we are reading from outside, so those cases must be handled.

Programs using protozero should include it with `-isystem` instead of with `-I` and then there will be no warnings.
