### ISSUE TITLE
Using `data_view` as key in std::map

### ISSUE THREAD

**Issue by springmeyer** [mapbox/protozero#82]
Trying this naively results in:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_base:63:21: error: invalid operands to binary expression
      ('const protozero::data_view' and 'const protozero::data_view')
        {return __x < __y;}
                ~~~ ^ ~~~
```

@joto is this a usecase we should support out of the box, or should this be implemented by the developer? I presume it requires adding a custom hash implementation.

**Comment by joto** [comment]
To support `std::map` you need an implementation for `operator<()`, to support `std::unordered_map` you need a hash. Both of this could be easily implemented, but they can easily lead to confusion for the developer, because the `data_view` only points into some memory held by somebody else, most likely in this case the protocol buffers message we are decoding. So presumable you want to put this information  into a map/unordered_map to keep it around, but it will have dangling pointers once the original message is gone. I am sure this could be useful in some cases, but really confusing in others. What use cases did you have in mind?

**Comment by joto** [comment]
There is another aspect here: `data_view` really is a stopgap used until we have `string_view` in C++17. You can already use `string_view` (or any other class) instead (see [doc](https://github.com/mapbox/protozero/blob/master/doc/advanced.md#protozero_use_view)). If we keep adding features to `data_view` we really have to make sure that they are compatible so that it will be easy to switch later. `std::string_view` supports the `operator<()` and there is a specialization for `std::hash` which means on the one hand: it makes sense to have theses ops, too. But on the other hand it means: Another thing we need to implement and make damn sure it is compatible with the `std` implementation.

**Comment by springmeyer** [comment]
Thanks @joto for this discussion.

> What use cases did you have in mind?

The usecase that prompted me to notice this issue and want to learn more was experimenting with this additional interface in vtzero:


```diff
diff --git a/include/vtzero/reader.hpp b/include/vtzero/reader.hpp
index f375a84..07a146c 100644
--- a/include/vtzero/reader.hpp
+++ b/include/vtzero/reader.hpp
@@ -776,6 +776,29 @@ namespace vtzero {
             return layer_iterator{};
         }
 
+        std::map<std::string,data_view> layers() const {
+            std::map<std::string,data_view> lays;
+            protozero::pbf_message<detail::pbf_tile> reader{m_data};
+
+            try {
+                while (reader.next(detail::pbf_tile::layers, protozero::pbf_wire_type::length_delimited)) {
+                    const auto layer_data = reader.get_view();
+                    protozero::pbf_message<detail::pbf_layer> layer_reader{layer_data};
+                    if (layer_reader.next(detail::pbf_layer::name, protozero::pbf_wire_type::length_delimited)) {
+                            lays.emplace(layer_reader.get_string(),layer_data);
+                    } else {
+                        // 4.1 "A layer MUST contain a name field."
+                        throw format_exception{"missing name in layer (spec 4.1)"};
+                    }
+                }
+            } catch (const protozero::exception&) {
+                // convert protozero exceptions into vtzero exception
+                throw protocol_buffers_exception{};
+            }
+
+            return lays;
+        }
+
         /**
          * Returns the layer with the specified zero-based index.
          *
```

Currently `vtzero` only allows accessing a layer by name or idx. I was worried that in the case where you are needing to query for a given layer in a `vtzero::vector_tile` multiple times it would be faster to decode all the layers like above, into a `std::map`, and then grab them that way (rather than needing to iterate the protobuf each time). However I have yet to prove that this approach is faster in practice, so my usecase is not critical at this point - only a curiosity.

I'm okay closing this for now and re-opening if the need is greater and more clear.

**Comment by springmeyer** [comment]
Oh, and of course I failed to mention that the above example diff actually uses a `std::string`, which works fine. The compile error happened when I tried to do `std::map<data_view,data_view> lays` to save on the allocation from `layer_reader.get_string()` .
